<a href="https://colab.research.google.com/github/Tahsin22201243/Machine-Learning/blob/main/Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Set B**

# 1. Create an array with values from 0 to 9 and extract all odd numbers.

In [1]:
import numpy as np

# Create array
arr = np.arange(0, 10)
print("Original Array:", arr)
print("Shape:", arr.shape)

# Extract odd numbers
odd_numbers = arr[arr % 2 != 0]
print("Odd Numbers:", odd_numbers)
print("Shape:", odd_numbers.shape)

Original Array: [0 1 2 3 4 5 6 7 8 9]
Shape: (10,)
Odd Numbers: [1 3 5 7 9]
Shape: (5,)


2. Extract the first two rows and first two columns from a 4×4 NumPy array.


In [2]:
# Create 4x4 array
arr_4x4 = np.arange(1, 17).reshape(4, 4)
print("Original Array:\n", arr_4x4)
print("Shape:", arr_4x4.shape)

# Extract first 2 rows and first 2 columns
sub_array = arr_4x4[:2, :2]
print("Extracted Sub-array:\n", sub_array)
print("Shape:", sub_array.shape)

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Shape: (4, 4)
Extracted Sub-array:
 [[1 2]
 [5 6]]
Shape: (2, 2)


3. Filter DataFrame rows where "Age" > 25.

In [8]:
import pandas as pd

# Sample DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [22, 28, 35, 22],
    "Salary": [30000, 40000, 50000, 35000]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# Filter rows
filtered_df = df[df["Age"] > 25]
print("\nFiltered DataFrame (Age > 25):\n", filtered_df)
print("Shape:", filtered_df.shape)

Original DataFrame:
       Name  Age  Salary
0    Alice   22   30000
1      Bob   28   40000
2  Charlie   35   50000
3    David   22   35000

Filtered DataFrame (Age > 25):
       Name  Age  Salary
1      Bob   28   40000
2  Charlie   35   50000
Shape: (2, 3)


4. Select only "Name" and "Salary" columns from existing DataFrame.

In [9]:
selected_columns = df[["Name", "Salary"]]
print("Selected Columns:\n", selected_columns)
print("Shape:", selected_columns.shape)

Selected Columns:
       Name  Salary
0    Alice   30000
1      Bob   40000
2  Charlie   50000
3    David   35000
Shape: (4, 2)


5. Find and print unique values in a specific column.

In [10]:
unique_values = df["Age"].unique()
print("Unique Age Values:", unique_values)
print("Shape:", unique_values.shape)

Unique Age Values: [22 28 35]
Shape: (3,)


# **Set A:**
# 1. Create a 1D array of 10 random integers between 1 and 50.**bold text**

In [11]:
import numpy as np

# Create 1D array
arr = np.random.randint(1, 51, 10)
print("Original 1D Array:", arr)
print("Shape:", arr.shape)

Original 1D Array: [46  2  4 34  8 34 16 49 28  4]
Shape: (10,)


2. Reshape the above 10-element array into a 2×5 matrix.

In [12]:
reshaped_arr = arr.reshape(2, 5)
print("Reshaped 2x5 Matrix:\n", reshaped_arr)
print("Shape:", reshaped_arr.shape)

Reshaped 2x5 Matrix:
 [[46  2  4 34  8]
 [34 16 49 28  4]]
Shape: (2, 5)


3. Create a DataFrame from a dictionary containing names and marks of 3 students.

In [13]:
import pandas as pd

# Dictionary
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

print("Student DataFrame:\n", df)
print("Shape:", df.shape)

Student DataFrame:
       Name  Marks
0    Alice     85
1      Bob     90
2  Charlie     78
Shape: (3, 2)


4. Use the head() function to display only the first 2 rows.

In [14]:
first_two = df.head(2)
print("First 2 Rows:\n", first_two)
print("Shape:", first_two.shape)

First 2 Rows:
     Name  Marks
0  Alice     85
1    Bob     90
Shape: (2, 2)


5. Rename one column using the rename() method.

In [15]:
df_renamed = df.rename(columns={"Marks": "Score"})

print("Renamed DataFrame:\n", df_renamed)
print("Shape:", df_renamed.shape)

Renamed DataFrame:
       Name  Score
0    Alice     85
1      Bob     90
2  Charlie     78
Shape: (3, 2)
