<a href="https://colab.research.google.com/github/Tahsin22201243/Machine-Learning/blob/main/Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create an array with values from 0 to 9 and extract all odd numbers.

In [1]:
import numpy as np

# Create array
arr = np.arange(0, 10)
print("Original Array:", arr)
print("Shape:", arr.shape)

# Extract odd numbers
odd_numbers = arr[arr % 2 != 0]
print("Odd Numbers:", odd_numbers)
print("Shape:", odd_numbers.shape)

Original Array: [0 1 2 3 4 5 6 7 8 9]
Shape: (10,)
Odd Numbers: [1 3 5 7 9]
Shape: (5,)


Extract the first two rows and first two columns from a 4×4 NumPy array.


In [2]:
# Create 4x4 array
arr_4x4 = np.arange(1, 17).reshape(4, 4)
print("Original Array:\n", arr_4x4)
print("Shape:", arr_4x4.shape)

# Extract first 2 rows and first 2 columns
sub_array = arr_4x4[:2, :2]
print("Extracted Sub-array:\n", sub_array)
print("Shape:", sub_array.shape)

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Shape: (4, 4)
Extracted Sub-array:
 [[1 2]
 [5 6]]
Shape: (2, 2)
